/**********************************************************************
 * Extern for behave.js
 * Everything was added manually by RJ.
 **********************************************************************/
const Module = {};

Module.SIGContainAdapter = class {
  constructor() {}
  doContainRun() {}
  addResource() {}
  setAttackDistance() {}
  setFireStartTime() {}
  setLwRatio() {}
  setMaxFireSize() {}
  setMaxFireTime() {}
  setMaxSteps() {}
  setMinSteps() {}
  setReportRate() {}
  setReportSize() {}
  setRetry() {}
  setTactic() {}
  removeAllResources() {}
  removeResourceWithThisDesc() {}
  removeResourceAt() {}
  removeAllResourcesWithThisDesc() {}
  getContainmentStatus() {}
  getFinalContainmentArea() {}
  getFinalCost() {}
  getFinalFireLineLength() {}
  getFinalFireSize() {}
  getFinalTimeSinceReport() {}
  getFireSizeAtInitialAttack() {}
  getPerimeterAtContainment() {}
  getPerimeterAtInitialAttack() {}
  getResourcesUsed() {}
};

Module.SIGSurface = class {
  constructor() {}
  calculateFlameLength() {}
  doSurfaceRun() {}
  doSurfaceRunInDirectionOfInterest() {}
  doSurfaceRunInDirectionOfMaxSpread() {}
  getAgeOfRough() {}
  getAspect() {}
  getAspenCuringLevel() {}
  getAspenDBH() {}
  getAspenFireSeverity() {}
  getAspenFuelModelNumber() {}
  getAspenLoadDeadOneHour() {}
  getAspenLoadDeadTenHour() {}
  getAspenLoadLiveHerbaceous() {}
  getAspenLoadLiveWoody() {}
  getAspenSavrDeadOneHour() {}
  getAspenSavrDeadTenHour() {}
  getAspenSavrLiveHerbaceous() {}
  getAspenSavrLiveWoody() {}
  getBackingFirelineIntensity() {}
  getBackingFlameLength() {}
  getBackingSpreadDistance() {}
  getBackingSpreadRate() {}
  getBulkDensity() {}
  getCanopyCover() {}
  getCanopyHeight() {}
  getChaparralAge() {}
  getChaparralDaysSinceMayFirst() {}
  getChaparralDeadFuelFraction() {}
  getChaparralDeadMoistureOfExtinction() {}
  getChaparralDensity() {}
  getChaparralFuelBedDepth() {}
  getChaparralFuelDeadLoadFraction() {}
  getChaparralFuelType() {}
  getChaparralHeatOfCombustion() {}
  getChaparralLiveMoistureOfExtinction() {}
  getChaparralLoadDeadHalfInchToLessThanOneInch() {}
  getChaparralLoadDeadLessThanQuarterInch() {}
  getChaparralLoadDeadOneInchToThreeInch() {}
  getChaparralLoadDeadQuarterInchToLessThanHalfInch() {}
  getChaparralLoadLiveHalfInchToLessThanOneInch() {}
  getChaparralLoadLiveLeaves() {}
  getChaparralLoadLiveOneInchToThreeInch() {}
  getChaparralLoadLiveQuarterInchToLessThanHalfInch() {}
  getChaparralLoadLiveStemsLessThanQuaterInch() {}
  getChaparralMoisture() {}
  getChaparralTotalDeadFuelLoad() {}
  getChaparralTotalFuelLoad() {}
  getChaparralTotalLiveFuelLoad() {}
  getCharacteristicMoistureByLifeState() {}
  getCharacteristicMoistureDead() {}
  getCharacteristicMoistureLive() {}
  getCharacteristicSAVR() {}
  getCrownRatio() {}
  getDirectionOfInterest() {}
  getDirectionOfMaxSpread() {}
  getElapsedTime() {}
  getEllipticalA() {}
  getEllipticalB() {}
  getEllipticalC() {}
  getFireArea() {}
  getFireEccentricity() {}
  getFireLengthToWidthRatio() {}
  getFirePerimeter() {}
  getFirelineIntensity() {}
  getFlameLength() {}
  getFlankingFirelineIntensity() {}
  getFlankingFlameLength() {}
  getFlankingSpreadDistance() {}
  getFlankingSpreadRate() {}
  getFuelCode() {}
  getFuelHeatOfCombustionDead() {}
  getFuelHeatOfCombustionLive() {}
  getFuelLoadHundredHour() {}
  getFuelLoadLiveHerbaceous() {}
  getFuelLoadLiveWoody() {}
  getFuelLoadOneHour() {}
  getFuelLoadTenHour() {}
  getFuelModelNumber() {}
  getFuelMoistureOfExtinctionDead() {}
  getFuelName() {}
  getFuelSavrLiveHerbaceous() {}
  getFuelSavrLiveWoody() {}
  getFuelSavrOneHour() {}
  getFuelbedDepth() {}
  getHeadingToBackingRatio() {}
  getHeatPerUnitArea() {}
  getHeatSink() {}
  getHeatSource() {}
  getHeightOfUnderstory() {}
  getIsMoistureScenarioDefinedByIndex() {}
  getIsMoistureScenarioDefinedByName() {}
  getIsUsingChaparral() {}
  getIsUsingPalmettoGallberry() {}
  getIsUsingWesternAspen() {}
  getLiveFuelMoistureOfExtinction() {}
  getMidflameWindspeed() {}
  getMoistureDeadAggregateValue() {}
  getMoistureHundredHour() {}
  getMoistureInputMode() {}
  getMoistureLiveAggregateValue() {}
  getMoistureLiveHerbaceous() {}
  getMoistureLiveWoody() {}
  getMoistureOneHour() {}
  getMoistureScenarioDescriptionByIndex() {}
  getMoistureScenarioDescriptionByName() {}
  getMoistureScenarioHundredHourByIndex() {}
  getMoistureScenarioHundredHourByName() {}
  getMoistureScenarioIndexByName() {}
  getMoistureScenarioLiveHerbaceousByIndex() {}
  getMoistureScenarioLiveHerbaceousByName() {}
  getMoistureScenarioLiveWoodyByIndex() {}
  getMoistureScenarioLiveWoodyByName() {}
  getMoistureScenarioNameByIndex() {}
  getMoistureScenarioOneHourByIndex() {}
  getMoistureScenarioOneHourByName() {}
  getMoistureScenarioTenHourByIndex() {}
  getMoistureScenarioTenHourByName() {}
  getMoistureTenHour() {}
  getNumberOfMoistureScenarios() {}
  getOverstoryBasalArea() {}
  getPalmettoGallberryCoverage() {}
  getPalmettoGallberryHeatOfCombustionDead() {}
  getPalmettoGallberryHeatOfCombustionLive() {}
  getPalmettoGallberryMoistureOfExtinctionDead() {}
  getPalmettoGallberyDeadFineFuelLoad() {}
  getPalmettoGallberyDeadFoliageLoad() {}
  getPalmettoGallberyDeadMediumFuelLoad() {}
  getPalmettoGallberyFuelBedDepth() {}
  getPalmettoGallberyLitterLoad() {}
  getPalmettoGallberyLiveFineFuelLoad() {}
  getPalmettoGallberyLiveFoliageLoad() {}
  getPalmettoGallberyLiveMediumFuelLoad() {}
  getReactionIntensity() {}
  getResidenceTime() {}
  getSlope() {}
  getSlopeFactor() {}
  getSpreadDistance() {}
  getSpreadDistanceInDirectionOfInterest() {}
  getSpreadRate() {}
  getSpreadRateInDirectionOfInterest() {}
  getSurfaceFireReactionIntensityForLifeState() {}
  getWindAdjustmentFactorCalculationMethod() {}
  getWindAndSpreadOrientationMode() {}
  getWindDirection() {}
  getWindHeightInputMode() {}
  getWindSpeed() {}
  getWindUpslopeAlignmentMode() {}
  initializeMembers() {}
  isAllFuelLoadZero() {}
  isFuelDynamic() {}
  isFuelModelDefined() {}
  isFuelModelReserved() {}
  isMoistureClassInputNeededForCurrentFuelModel() {}
  isUsingTwoFuelModels() {}
  setAgeOfRough() {}
  setAspect() {}
  setAspenCuringLevel() {}
  setAspenDBH() {}
  setAspenFireSeverity() {}
  setAspenFuelModelNumber() {}
  setCanopyCover() {}
  setCanopyHeight() {}
  setChaparralFuelBedDepth() {}
  setChaparralFuelDeadLoadFraction() {}
  setChaparralFuelLoadInputMode() {}
  setChaparralFuelType() {}
  setChaparralTotalFuelLoad() {}
  setCrownRatio() {}
  setDirectionOfInterest() {}
  setElapsedTime() {}
  setFirstFuelModelNumber() {}
  setFuelModelNumber() {}
  setFuelModels() {}
  setHeightOfUnderstory() {}
  setIsUsingChaparral() {}
  setIsUsingPalmettoGallberry() {}
  setIsUsingWesternAspen() {}
  setMoistureDeadAggregate() {}
  setMoistureHundredHour() {}
  setMoistureInputMode() {}
  setMoistureLiveAggregate() {}
  setMoistureLiveHerbaceous() {}
  setMoistureLiveWoody() {}
  setMoistureOneHour() {}
  setMoistureScenarioByIndex() {}
  setMoistureScenarioByName() {}
  setMoistureScenarios() {}
  setMoistureTenHour() {}
  setOverstoryBasalArea() {}
  setPalmettoCoverage() {}
  setSecondFuelModelNumber() {}
  setSlope() {}
  setSurfaceFireSpreadDirectionMode() {}
  setSurfaceRunInDirectionOf() {}
  setTwoFuelModelsFirstFuelModelCoverage() {}
  setTwoFuelModelsMethod() {}
  setUserProvidedWindAdjustmentFactor() {}
  setWindAdjustmentFactorCalculationMethod() {}
  setWindAndSpreadOrientationMode() {}
  setWindDirection() {}
  setWindHeightInputMode() {}
  setWindSpeed() {}
  setWindUpslopeAlignmentMode() {}
  updateSurfaceInputs() {}
  updateSurfaceInputsForPalmettoGallbery() {}
  updateSurfaceInputsForTwoFuelModels() {}
  updateSurfaceInputsForWesternAspen() {}
};

Module.SIGCrown = class {
  constructor() {}
  getFireType() {}
  getIsMoistureScenarioDefinedByIndex() {}
  getIsMoistureScenarioDefinedByName() {}
  isAllFuelLoadZero() {}
  isFuelDynamic() {}
  isFuelModelDefined() {}
  isFuelModelReserved() {}
  setMoistureScenarioByIndex() {}
  setMoistureScenarioByName() {}
  getAspect() {}
  getCanopyBaseHeight() {}
  getCanopyBulkDensity() {}
  getCanopyCover() {}
  getCanopyHeight() {}
  getCriticalOpenWindSpeed() {}
  getCrownCriticalFireSpreadRate() {}
  getCrownCriticalSurfaceFirelineIntensity() {}
  getCrownCriticalSurfaceFlameLength() {}
  getCrownFireActiveRatio() {}
  getCrownFireArea() {}
  getCrownFirePerimeter() {}
  getCrownTransitionRatio() {}
  getCrownFireLengthToWidthRatio() {}
  getCrownFireSpreadDistance() {}
  getCrownFireSpreadRate() {}
  getCrownFirelineIntensity() {}
  getCrownFlameLength() {}
  getCrownFractionBurned() {}
  getCrownRatio() {}
  getFinalFirelineIntesity() {}
  getFinalHeatPerUnitArea() {}
  getFinalSpreadRate() {}
  getFuelHeatOfCombustionDead() {}
  getFuelHeatOfCombustionLive() {}
  getFuelLoadHundredHour() {}
  getFuelLoadLiveHerbaceous() {}
  getFuelLoadLiveWoody() {}
  getFuelLoadOneHour() {}
  getFuelLoadTenHour() {}
  getFuelMoistureOfExtinctionDead() {}
  getFuelSavrLiveHerbaceous() {}
  getFuelSavrLiveWoody() {}
  getFuelSavrOneHour() {}
  getFuelbedDepth() {}
  getMoistureFoliar() {}
  getMoistureHundredHour() {}
  getMoistureLiveHerbaceous() {}
  getMoistureLiveWoody() {}
  getMoistureOneHour() {}
  getMoistureScenarioHundredHourByIndex() {}
  getMoistureScenarioHundredHourByName() {}
  getMoistureScenarioLiveHerbaceousByIndex() {}
  getMoistureScenarioLiveHerbaceousByName() {}
  getMoistureScenarioLiveWoodyByIndex() {}
  getMoistureScenarioLiveWoodyByName() {}
  getMoistureScenarioOneHourByIndex() {}
  getMoistureScenarioOneHourByName() {}
  getMoistureScenarioTenHourByIndex() {}
  getMoistureScenarioTenHourByName() {}
  getMoistureTenHour() {}
  getSlope() {}
  getSurfaceFireSpreadDistance() {}
  getSurfaceFireSpreadRate() {}
  getWindDirection() {}
  getWindSpeed() {}
  getFuelModelNumber() {}
  getMoistureScenarioIndexByName() {}
  getNumberOfMoistureScenarios() {}
  getFuelCode() {}
  getFuelName() {}
  getMoistureScenarioDescriptionByIndex() {}
  getMoistureScenarioDescriptionByName() {}
  getMoistureScenarioNameByIndex() {}
  doCrownRunRothermel() {}
  doCrownRunScottAndReinhardt() {}
  initializeMembers() {}
  setAspect() {}
  setCanopyBaseHeight() {}
  setCanopyBulkDensity() {}
  setCanopyCover() {}
  setCanopyHeight() {}
  setCrownRatio() {}
  setFuelModelNumber() {}
  setCrownFireCalculationMethod() {}
  setElapsedTime() {}
  setFuelModels() {}
  setMoistureDeadAggregate() {}
  setMoistureFoliar() {}
  setMoistureHundredHour() {}
  setMoistureInputMode() {}
  setMoistureLiveAggregate() {}
  setMoistureLiveHerbaceous() {}
  setMoistureLiveWoody() {}
  setMoistureOneHour() {}
  setMoistureScenarios() {}
  setMoistureTenHour() {}
  setSlope() {}
  setUserProvidedWindAdjustmentFactor() {}
  setWindAdjustmentFactorCalculationMethod() {}
  setWindAndSpreadOrientationMode() {}
  setWindDirection() {}
  setWindHeightInputMode() {}
  setWindSpeed() {}
  updateCrownInputs() {}
  updateCrownsSurfaceInputs() {}
  getFinalFlameLength() {}
};

Module.SIGMortality = class {
  constructor() {}
  getBeetleDamage() {}
  getCrownDamageEquationCode() {}
  getCrownDamageEquationCodeAtSpeciesTableIndex() {}
  getCrownDamageEquationCodeFromSpeciesCode() {}
  getCrownDamageType() {}
  getEquationType() {}
  getEquationTypeAtSpeciesTableIndex() {}
  getFireSeverity() {}
  getFlameLengthOrScorchHeightSwitch() {}
  getRegion() {}
  getSpeciesRecordAtIndex() {}
  getSpeciesRecordBySpeciesCodeAndEquationType() {}
  checkIsInRegionAtSpeciesTableIndex() {}
  checkIsInRegionFromSpeciesCode() {}
  updateInputsForSpeciesCodeAndEquationType() {}
  calculateMortality() {}
  calculateScorchHeight() {}
  getBarkThickness() {}
  getBasalAreaKillled() {}
  getBasalAreaPostfire() {}
  getBasalAreaPrefire() {}
  getBoleCharHeight() {}
  getCambiumKillRating() {}
  getCrownDamage() {}
  getCrownRatio() {}
  getCalculatedScorchHeight() {}
  getDBH() {}
  getFlameLengthOrScorchHeightValue() {}
  getKilledTrees() {}
  getProbabilityOfMortality() {}
  getTotalPrefireTrees() {}
  getTreeCrownLengthScorched() {}
  getTreeCrownVolumeScorched() {}
  getTreeDensityPerUnitArea() {}
  getTreeHeight() {}
  postfireCanopyCover() {}
  prefireCanopyCover() {}
  getBarkEquationNumberAtSpeciesTableIndex() {}
  getBarkEquationNumberFromSpeciesCode() {}
  getCrownCoefficientCodeAtSpeciesTableIndex() {}
  getCrownCoefficientCodeFromSpeciesCode() {}
  getCrownScorchOrBoleCharEquationNumber() {}
  getMortalityEquationNumberAtSpeciesTableIndex() {}
  getMortalityEquationNumberFromSpeciesCode() {}
  getNumberOfRecordsInSpeciesTable() {}
  getSpeciesTableIndexFromSpeciesCode() {}
  getSpeciesTableIndexFromSpeciesCodeAndEquationType() {}
  getSpeciesCode() {}
  getSpeciesRecordVectorForRegion() {}
  getSpeciesRecordVectorForRegionAndEquationType() {}
  getCommonNameAtSpeciesTableIndex() {}
  getCommonNameFromSpeciesCode() {}
  getScientificNameAtSpeciesTableIndex() {}
  getScientificNameFromSpeciesCode() {}
  getSpeciesCodeAtSpeciesTableIndex() {}
  getRequiredFieldVector() {}
  setAirTemperature() {}
  setBeetleDamage() {}
  setBoleCharHeight() {}
  setCambiumKillRating() {}
  setCrownDamage() {}
  setCrownRatio() {}
  setDBH() {}
  setEquationType() {}
  setFireSeverity() {}
  setFirelineIntensity() {}
  setFlameLengthOrScorchHeightSwitch() {}
  setFlameLengthOrScorchHeightValue() {}
  setRegion() {}
  setSurfaceFireFlameLength() {}
  setSurfaceFireScorchHeight() {}
  setSpeciesCode() {}
  setTreeDensityPerUnitArea() {}
  setTreeHeight() {}
  getEquationTypeFromSpeciesCode() {}
};
