/**********************************************************************
 * Extern for katex
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var katex = {
  "ParseError": function () {},
  "SETTINGS_SCHEMA": {
    "colorIsTextColor": {
      "cli": {},
      "description": {},
      "type": {}
    },
    "displayMode": {
      "cli": {},
      "description": {},
      "type": {}
    },
    "errorColor": {
      "cli": {},
      "cliDescription": {},
      "cliProcessor": function () {},
      "default": {},
      "type": {}
    },
    "fleqn": {
      "description": {},
      "type": {}
    },
    "globalGroup": {
      "cli": {},
      "type": {}
    },
    "leqno": {
      "description": {},
      "type": {}
    },
    "macros": {
      "cli": {},
      "cliDefault": {},
      "cliDescription": {},
      "cliProcessor": function () {},
      "type": {}
    },
    "maxExpand": {
      "cli": {},
      "cliProcessor": function () {},
      "default": {},
      "description": {},
      "processor": function () {},
      "type": {}
    },
    "maxSize": {
      "cli": {},
      "cliProcessor": function () {},
      "default": {},
      "description": {},
      "processor": function () {},
      "type": {}
    },
    "minRuleThickness": {
      "cli": {},
      "cliProcessor": function () {},
      "description": {},
      "processor": function () {},
      "type": {}
    },
    "output": {
      "cli": {},
      "description": {},
      "type": {
        "enum": {}
      }
    },
    "strict": {
      "cli": {},
      "cliDefault": {},
      "description": {},
      "type": {}
    },
    "throwOnError": {
      "cli": {},
      "cliDescription": {},
      "default": {},
      "type": {}
    },
    "trust": {
      "cli": {},
      "description": {},
      "type": {}
    }
  },
  "__defineMacro": function () {},
  "__defineSymbol": function () {},
  "__domTree": {
    "Anchor": function () {},
    "LineNode": function () {},
    "PathNode": function () {},
    "Span": function () {},
    "SvgNode": function () {},
    "SymbolNode": function () {}
  },
  "__parse": function () {},
  "__renderToDomTree": function () {},
  "__renderToHTMLTree": function () {},
  "__setFontMetrics": function () {},
  "render": function () {},
  "renderToString": function () {},
  "version": {}
};
katex.__domTree.Anchor.prototype = {
  "hasClass": function () {},
  "setAttribute": function () {},
  "toMarkup": function () {},
  "toNode": function () {}
};
katex.__domTree.LineNode.prototype = {
  "toMarkup": function () {},
  "toNode": function () {}
};
katex.__domTree.PathNode.prototype = {
  "toMarkup": function () {},
  "toNode": function () {}
};
katex.__domTree.Span.prototype = {
  "hasClass": function () {},
  "setAttribute": function () {},
  "toMarkup": function () {},
  "toNode": function () {}
};
katex.__domTree.SvgNode.prototype = {
  "toMarkup": function () {},
  "toNode": function () {}
};
katex.__domTree.SymbolNode.prototype = {
  "hasClass": function () {},
  "toMarkup": function () {},
  "toNode": function () {}
};
/**********************************************************************
 * End Generated Extern for katex
/**********************************************************************/