(ns behave.lib.crown
  (:require [behave.lib.fuel-models :as fuel-models]))

;; Auto-generated by hatchet 🪓

(defn init
  ([]
   (init (fuel-models/init)))
  ([fuelModels]
   (js/Module.SIGCrown. fuelModels)))

(defn Crown [self rhs]
  (.Crown self rhs))

(defn doCrownRun [self]
  (.doCrownRun self))

(defn doCrownRunRothermel [self]
  (.doCrownRunRothermel self))

(defn doCrownRunScottAndReinhardt [self]
  (.doCrownRunScottAndReinhardt self))

(defn getAspect [self]
  (.getAspect self))

(defn getCanopyBaseHeight [self canopyHeightUnits]
  (.getCanopyBaseHeight self canopyHeightUnits))

(defn getCanopyBulkDensity [self canopyBulkDensityUnits]
  (.getCanopyBulkDensity self canopyBulkDensityUnits))

(defn getCanopyCover [self canopyCoverUnits]
  (.getCanopyCover self canopyCoverUnits))

(defn getCanopyHeight [self canopyHeighUnits]
  (.getCanopyHeight self canopyHeighUnits))

(defn getCriticalOpenWindSpeed [self speedUnits]
  (.getCriticalOpenWindSpeed self speedUnits))

(defn getCrownCriticalFireSpreadRate [self spreadRateUnits]
  (.getCrownCriticalFireSpreadRate self spreadRateUnits))

(defn getCrownCriticalSurfaceFirelineIntensity [self firelineIntensityUnits]
  (.getCrownCriticalSurfaceFirelineIntensity self firelineIntensityUnits))

(defn getCrownCriticalSurfaceFlameLength [self flameLengthUnits]
  (.getCrownCriticalSurfaceFlameLength self flameLengthUnits))

(defn getCrownFireActiveRatio [self]
  (.getCrownFireActiveRatio self))

(defn getCrownFireArea [self areaUnits]
  (.getCrownFireArea self areaUnits))

(defn getCrownFirePerimeter [self lengthUnits]
  (.getCrownFirePerimeter self lengthUnits))

(defn getCrownFireLengthToWidthRatio [self]
  (.getCrownFireLengthToWidthRatio self))

(defn getCrownFireSpreadDistance [self lengthUnits]
  (.getCrownFireSpreadDistance self lengthUnits))

(defn getCrownFireSpreadRate [self spreadRateUnits]
  (.getCrownFireSpreadRate self spreadRateUnits))

(defn getCrownFirelineIntensity [self firelineIntensityUnits]
  (.getCrownFirelineIntensity self firelineIntensityUnits))

(defn getCrownFlameLength [self flameLengthUnits]
  (.getCrownFlameLength self flameLengthUnits))

(defn getCrownFractionBurned [self]
  (.getCrownFractionBurned self))

(defn getCrownRatio [self crownRatioUnits]
  (.getCrownRatio self crownRatioUnits))

(defn getCrownTransitionRatio [self]
  (.getCrownTransitionRatio self))

(defn getFinalFirelineIntesity [self firelineIntensityUnits]
  (.getFinalFirelineIntesity self firelineIntensityUnits))

(defn getFinalFlameLength [self flameLengthUnits]
  (.getFinalFlameLength self flameLengthUnits))

(defn getFinalHeatPerUnitArea [self heatPerUnitAreaUnits]
  (.getFinalHeatPerUnitArea self heatPerUnitAreaUnits))

(defn getFinalSpreadRate [self spreadRateUnits]
  (.getFinalSpreadRate self spreadRateUnits))

(defn getFinalSpreadDistance [self lengthUnits]
  (.getFinalSpreadDistance self lengthUnits))

(defn getFinalFireArea [self areaUnits]
  (.getFinalFireArea self areaUnits))

(defn getFinalFirePerimeter [self lengthUnits]
  (.getFinalFirePerimeter self lengthUnits))

(defn getFireType [self]
  (.getFireType self))

(defn getFuelCode [self fuelModelNumber]
  (.getFuelCode self fuelModelNumber))

(defn getFuelHeatOfCombustionDead [self fuelModelNumber heatOfCombustionUnits]
  (.getFuelHeatOfCombustionDead self fuelModelNumber heatOfCombustionUnits))

(defn getFuelHeatOfCombustionLive [self fuelModelNumber heatOfCombustionUnits]
  (.getFuelHeatOfCombustionLive self fuelModelNumber heatOfCombustionUnits))

(defn getFuelLoadHundredHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadHundredHour self fuelModelNumber loadingUnits))

(defn getFuelLoadLiveHerbaceous [self fuelModelNumber loadingUnits]
  (.getFuelLoadLiveHerbaceous self fuelModelNumber loadingUnits))

(defn getFuelLoadLiveWoody [self fuelModelNumber loadingUnits]
  (.getFuelLoadLiveWoody self fuelModelNumber loadingUnits))

(defn getFuelLoadOneHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadOneHour self fuelModelNumber loadingUnits))

(defn getFuelLoadTenHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadTenHour self fuelModelNumber loadingUnits))

(defn getFuelModelNumber [self]
  (.getFuelModelNumber self))

(defn getFuelMoistureOfExtinctionDead [self fuelModelNumber moistureUnits]
  (.getFuelMoistureOfExtinctionDead self fuelModelNumber moistureUnits))

(defn getFuelName [self fuelModelNumber]
  (.getFuelName self fuelModelNumber))

(defn getFuelSavrLiveHerbaceous [self fuelModelNumber savrUnits]
  (.getFuelSavrLiveHerbaceous self fuelModelNumber savrUnits))

(defn getFuelSavrLiveWoody [self fuelModelNumber savrUnits]
  (.getFuelSavrLiveWoody self fuelModelNumber savrUnits))

(defn getFuelSavrOneHour [self fuelModelNumber savrUnits]
  (.getFuelSavrOneHour self fuelModelNumber savrUnits))

(defn getFuelbedDepth [self fuelModelNumber lengthUnits]
  (.getFuelbedDepth self fuelModelNumber lengthUnits))

(defn getIsMoistureScenarioDefinedByIndex [self index]
  (.getIsMoistureScenarioDefinedByIndex self index))

(defn getIsMoistureScenarioDefinedByName [self name]
  (.getIsMoistureScenarioDefinedByName self name))

(defn getMoistureFoliar [self moistureUnits]
  (.getMoistureFoliar self moistureUnits))

(defn getMoistureHundredHour [self moistureUnits]
  (.getMoistureHundredHour self moistureUnits))

(defn getMoistureLiveHerbaceous [self moistureUnits]
  (.getMoistureLiveHerbaceous self moistureUnits))

(defn getMoistureLiveWoody [self moistureUnits]
  (.getMoistureLiveWoody self moistureUnits))

(defn getMoistureOneHour [self moistureUnits]
  (.getMoistureOneHour self moistureUnits))

(defn getMoistureScenarioDescriptionByIndex [self index]
  (.getMoistureScenarioDescriptionByIndex self index))

(defn getMoistureScenarioDescriptionByName [self name]
  (.getMoistureScenarioDescriptionByName self name))

(defn getMoistureScenarioHundredHourByIndex [self index]
  (.getMoistureScenarioHundredHourByIndex self index))

(defn getMoistureScenarioHundredHourByName [self name]
  (.getMoistureScenarioHundredHourByName self name))

(defn getMoistureScenarioIndexByName [self name]
  (.getMoistureScenarioIndexByName self name))

(defn getMoistureScenarioLiveHerbaceousByIndex [self index]
  (.getMoistureScenarioLiveHerbaceousByIndex self index))

(defn getMoistureScenarioLiveHerbaceousByName [self name]
  (.getMoistureScenarioLiveHerbaceousByName self name))

(defn getMoistureScenarioLiveWoodyByIndex [self index]
  (.getMoistureScenarioLiveWoodyByIndex self index))

(defn getMoistureScenarioLiveWoodyByName [self name]
  (.getMoistureScenarioLiveWoodyByName self name))

(defn getMoistureScenarioNameByIndex [self index]
  (.getMoistureScenarioNameByIndex self index))

(defn getMoistureScenarioOneHourByIndex [self index]
  (.getMoistureScenarioOneHourByIndex self index))

(defn getMoistureScenarioOneHourByName [self name]
  (.getMoistureScenarioOneHourByName self name))

(defn getMoistureScenarioTenHourByIndex [self index]
  (.getMoistureScenarioTenHourByIndex self index))

(defn getMoistureScenarioTenHourByName [self name]
  (.getMoistureScenarioTenHourByName self name))

(defn getMoistureTenHour [self moistureUnits]
  (.getMoistureTenHour self moistureUnits))

(defn getNumberOfMoistureScenarios [self]
  (.getNumberOfMoistureScenarios self))

(defn getSlope [self slopeUnits]
  (.getSlope self slopeUnits))

(defn getSurfaceFireSpreadDistance [self lengthUnits]
  (.getSurfaceFireSpreadDistance self lengthUnits))

(defn getSurfaceFireSpreadRate [self spreadRateUnits]
  (.getSurfaceFireSpreadRate self spreadRateUnits))

(defn getWindDirection [self]
  (.getWindDirection self))

(defn getWindSpeed [self windSpeedUnits windHeightInputMode]
  (.getWindSpeed self windSpeedUnits windHeightInputMode))

(defn initializeMembers [self]
  (.initializeMembers self))

(defn isAllFuelLoadZero [self fuelModelNumber]
  (.isAllFuelLoadZero self fuelModelNumber))

(defn isFuelDynamic [self fuelModelNumber]
  (.isFuelDynamic self fuelModelNumber))

(defn isFuelModelDefined [self fuelModelNumber]
  (.isFuelModelDefined self fuelModelNumber))

(defn isFuelModelReserved [self fuelModelNumber]
  (.isFuelModelReserved self fuelModelNumber))

(defn setAspect [self aspect]
  (.setAspect self aspect))

(defn setCanopyBaseHeight [self canopyBaseHeight canopyHeightUnits]
  (.setCanopyBaseHeight self canopyBaseHeight canopyHeightUnits))

(defn setCanopyBulkDensity [self canopyBulkDensity densityUnits]
  (.setCanopyBulkDensity self canopyBulkDensity densityUnits))

(defn setCanopyCover [self canopyCover coverUnits]
  (.setCanopyCover self canopyCover coverUnits))

(defn setCanopyHeight [self canopyHeight canopyHeightUnits]
  (.setCanopyHeight self canopyHeight canopyHeightUnits))

(defn setCrownFireCalculationMethod [self CrownFireCalculationMethod]
  (.setCrownFireCalculationMethod self CrownFireCalculationMethod))

(defn setCrownRatio [self crownRatio crownRatioUnits]
  (.setCrownRatio self crownRatio crownRatioUnits))

(defn setElapsedTime [self elapsedTime timeUnits]
  (.setElapsedTime self elapsedTime timeUnits))

(defn setFuelModelNumber [self fuelModelNumber]
  (.setFuelModelNumber self fuelModelNumber))

(defn setFuelModels [self fuelModels]
  (.setFuelModels self fuelModels))

(defn setMoistureDeadAggregate [self moistureDead moistureUnits]
  (.setMoistureDeadAggregate self moistureDead moistureUnits))

(defn setMoistureFoliar [self foliarMoisture moistureUnits]
  (.setMoistureFoliar self foliarMoisture moistureUnits))

(defn setMoistureHundredHour [self moistureHundredHour moistureUnits]
  (.setMoistureHundredHour self moistureHundredHour moistureUnits))

(defn setMoistureInputMode [self moistureInputMode]
  (.setMoistureInputMode self moistureInputMode))

(defn setMoistureLiveAggregate [self moistureLive moistureUnits]
  (.setMoistureLiveAggregate self moistureLive moistureUnits))

(defn setMoistureLiveHerbaceous [self moistureLiveHerbaceous moistureUnits]
  (.setMoistureLiveHerbaceous self moistureLiveHerbaceous moistureUnits))

(defn setMoistureLiveWoody [self moistureLiveWoody moistureUnits]
  (.setMoistureLiveWoody self moistureLiveWoody moistureUnits))

(defn setMoistureOneHour [self moistureOneHour moistureUnits]
  (.setMoistureOneHour self moistureOneHour moistureUnits))

(defn setMoistureScenarioByIndex [self moistureScenarioIndex]
  (.setMoistureScenarioByIndex self moistureScenarioIndex))

(defn setMoistureScenarioByName [self moistureScenarioName]
  (.setMoistureScenarioByName self moistureScenarioName))

(defn setMoistureScenarios [self moistureScenarios]
  (.setMoistureScenarios self moistureScenarios))

(defn setMoistureTenHour [self moistureTenHour moistureUnits]
  (.setMoistureTenHour self moistureTenHour moistureUnits))

(defn setSlope [self slope slopeUnits]
  (.setSlope self slope slopeUnits))

(defn setUserProvidedWindAdjustmentFactor [self userProvidedWindAdjustmentFactor]
  (.setUserProvidedWindAdjustmentFactor self userProvidedWindAdjustmentFactor))

(defn setWindAdjustmentFactorCalculationMethod [self windAdjustmentFactorCalculationMethod]
  (.setWindAdjustmentFactorCalculationMethod self windAdjustmentFactorCalculationMethod))

(defn setWindAndSpreadOrientationMode [self windAndSpreadAngleMode]
  (.setWindAndSpreadOrientationMode self windAndSpreadAngleMode))

(defn setWindDirection [self windDirection]
  (.setWindDirection self windDirection))

(defn setWindHeightInputMode [self windHeightInputMode]
  (.setWindHeightInputMode self windHeightInputMode))

(defn setWindSpeed [self windSpeed windSpeedUnits]
  (.setWindSpeed self windSpeed windSpeedUnits))

(defn updateCrownInputs [self fuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureFoliar moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyBaseHeight canopyHeightUnits crownRatio canopyBulkDensity densityUnits]
  (.updateCrownInputs self fuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureFoliar moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyBaseHeight canopyHeightUnits crownRatio canopyBulkDensity densityUnits))

(defn updateCrownsSurfaceInputs [self fuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio]
  (.updateCrownsSurfaceInputs self fuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio))
