(ns behave.lib.fuel-models)

;; Auto-generated by hatchet 🪓
(defn init []
  (js/Module.SIGFuelModels.))

(defn getHeatOfCombustionLive [self fuelModelNumber heatOfCombustionUnits]
  (.getHeatOfCombustionLive self fuelModelNumber heatOfCombustionUnits))

(defn getFuelName [self fuelModelNumber]
  (.getFuelName self fuelModelNumber))

(defn getFuelLoadLiveWoody [self fuelModelNumber loadingUnits]
  (.getFuelLoadLiveWoody self fuelModelNumber loadingUnits))

(defn isAllFuelLoadZero [self fuelModelNumber]
  (.isAllFuelLoadZero self fuelModelNumber))

(defn getSavrLiveHerbaceous [self fuelModelNumber savrUnits]
  (.getSavrLiveHerbaceous self fuelModelNumber savrUnits))

(defn getHeatOfCombustionDead [self fuelModelNumber heatOfCombustionUnits]
  (.getHeatOfCombustionDead self fuelModelNumber heatOfCombustionUnits))

(defn getFuelCode [self fuelModelNumber]
  (.getFuelCode self fuelModelNumber))

(defn operator= [self rhs]
  (.operator= self rhs))

(defn isFuelModelReserved [self fuelModelNumber]
  (.isFuelModelReserved self fuelModelNumber))

(defn getMoistureOfExtinctionDead [self fuelModelNumber moistureUnits]
  (.getMoistureOfExtinctionDead self fuelModelNumber moistureUnits))

(defn setCustomFuelModel [self fuelModelNumber code name fuelBedDepth lengthUnits moistureOfExtinctionDead moistureUnits heatOfCombustionDead heatOfCombustionLive heatOfCombustionUnits fuelLoadOneHour fuelLoadTenHour fuelLoadHundredHour fuelLoadLiveHerbaceous fuelLoadLiveWoody loadingUnits savrOneHour savrLiveHerbaceous savrLiveWoody savrUnits isDynamic]
  (.setCustomFuelModel self fuelModelNumber code name fuelBedDepth lengthUnits moistureOfExtinctionDead moistureUnits heatOfCombustionDead heatOfCombustionLive heatOfCombustionUnits fuelLoadOneHour fuelLoadTenHour fuelLoadHundredHour fuelLoadLiveHerbaceous fuelLoadLiveWoody loadingUnits savrOneHour savrLiveHerbaceous savrLiveWoody savrUnits isDynamic))

(defn clearCustomFuelModel [self fuelModelNumber]
  (.clearCustomFuelModel self fuelModelNumber))

(defn getFuelLoadLiveHerbaceous [self fuelModelNumber loadingUnits]
  (.getFuelLoadLiveHerbaceous self fuelModelNumber loadingUnits))

(defn getSavrOneHour [self fuelModelNumber savrUnits]
  (.getSavrOneHour self fuelModelNumber savrUnits))

(defn getFuelLoadTenHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadTenHour self fuelModelNumber loadingUnits))

(defn getIsDynamic [self fuelModelNumber]
  (.getIsDynamic self fuelModelNumber))

(defn getFuelLoadOneHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadOneHour self fuelModelNumber loadingUnits))

(defn getFuelLoadHundredHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadHundredHour self fuelModelNumber loadingUnits))

(defn isFuelModelDefined [self fuelModelNumber]
  (.isFuelModelDefined self fuelModelNumber))

(defn getFuelbedDepth [self fuelModelNumber lengthUnits]
  (.getFuelbedDepth self fuelModelNumber lengthUnits))

(defn getSavrLiveWoody [self fuelModelNumber savrUnits]
  (.getSavrLiveWoody self fuelModelNumber savrUnits))
