;; Auto-generated by hatchet 🪓
(ns behave.lib.ignite)

(defn init []
  (js/Module.SIGIgnite.))

(defn calculateFirebrandIgnitionProbability [self]
  (.calculateFirebrandIgnitionProbability self))

(defn getFirebrandIgnitionProbability [self desiredUnits]
  (.getFirebrandIgnitionProbability self desiredUnits))

(defn setAirTemperature [self airTemperature temperatureUnites]
  (.setAirTemperature self airTemperature temperatureUnites))

(defn getMoistureHundredHour [self desiredUnits]
  (.getMoistureHundredHour self desiredUnits))

(defn getLightningChargeType [self]
  (.getLightningChargeType self))

(defn setMoistureOneHour [self moistureOneHour moistureUnits]
  (.setMoistureOneHour self moistureOneHour moistureUnits))

(defn calculateLightningIgnitionProbability [self desiredUnits]
  (.calculateLightningIgnitionProbability self desiredUnits))

(defn getDuffDepth [self desiredUnits]
  (.getDuffDepth self desiredUnits))

(defn setIgnitionFuelBedType [self fuelBedType_]
  (.setIgnitionFuelBedType self fuelBedType_))

(defn setSunShade [self sunShade sunShadeUnits]
  (.setSunShade self sunShade sunShadeUnits))

(defn getAirTemperature [self desiredUnits]
  (.getAirTemperature self desiredUnits))

(defn getFuelTemperature [self desiredUnits]
  (.getFuelTemperature self desiredUnits))

(defn isFuelDepthNeeded [self]
  (.isFuelDepthNeeded self))

(defn setMoistureHundredHour [self moistureHundredHour moistureUnits]
  (.setMoistureHundredHour self moistureHundredHour moistureUnits))

(defn getSunShade [self desiredUnits]
  (.getSunShade self desiredUnits))

(defn initializeMembers [self]
  (.initializeMembers self))

(defn getFuelBedType [self]
  (.getFuelBedType self))

(defn getMoistureOneHour [self desiredUnits]
  (.getMoistureOneHour self desiredUnits))

(defn setLightningChargeType [self lightningChargeType]
  (.setLightningChargeType self lightningChargeType))

(defn setDuffDepth [self duffDepth lengthUnits]
  (.setDuffDepth self duffDepth lengthUnits))

(defn updateIgniteInputs [self moistureOneHour moistureHundredHour moistureUnits airTemperature temperatureUnits sunShade sunShadeUnits fuelBedType duffDepth duffDepthUnits lightningChargeType]
  (.updateIgniteInputs self moistureOneHour moistureHundredHour moistureUnits airTemperature temperatureUnits sunShade sunShadeUnits fuelBedType duffDepth duffDepthUnits lightningChargeType))
