(ns behave.lib.moisture-scenarios)

;; Auto-generated by hatchet 🪓

(defn init []
  (js/Module.SIGMoistureScenarios.))

(defn getMoistureScenarioLiveHerbaceousByIndex [self index]
  (.then self (fn [self] (.getMoistureScenarioLiveHerbaceousByIndex self index))))

(defn getMoistureScenarioHundredHourByIndex [self index]
  (.then self (fn [self] (.getMoistureScenarioHundredHourByIndex self index))))

(defn MoistureScenarios [self rhs]
  (.then self (fn [self] (.MoistureScenarios self rhs))))

(defn getMoistureScenarioLiveWoodyByIndex [self index]
  (.then self (fn [self] (.getMoistureScenarioLiveWoodyByIndex self index))))

(defn getMoistureScenarioIndexByName [self name]
  (.then self (fn [self] (.getMoistureScenarioIndexByName self name))))

(defn getMoistureScenarioDescriptionByName [self name]
  (.then self (fn [self] (.getMoistureScenarioDescriptionByName self name))))

(defn getMoistureScenarioHundredHourByName [self name]
  (.then self (fn [self] (.getMoistureScenarioHundredHourByName self name))))

(defn getMoistureScenarioOneHourByName [self name]
  (.then self (fn [self] (.getMoistureScenarioOneHourByName self name))))

(defn getNumberOfMoistureScenarios [self]
  (.then self (fn [self] (.getNumberOfMoistureScenarios self))))

(defn getIsMoistureScenarioDefinedByName [self name]
  (.then self (fn [self] (.getIsMoistureScenarioDefinedByName self name))))

(defn getMoistureScenarioDescriptionByIndex [self index]
  (.then self (fn [self] (.getMoistureScenarioDescriptionByIndex self index))))

(defn operator= [self rhs]
  (.then self (fn [self] (.operator= self rhs))))

(defn getMoistureScenarioNameByIndex [self index]
  (.then self (fn [self] (.getMoistureScenarioNameByIndex self index))))

(defn getMoistureScenarioLiveWoodyByName [self name]
  (.then self (fn [self] (.getMoistureScenarioLiveWoodyByName self name))))

(defn getMoistureScenarioLiveHerbaceousByName [self name]
  (.then self (fn [self] (.getMoistureScenarioLiveHerbaceousByName self name))))

(defn getMoistureScenarioTenHourByName [self name]
  (.then self (fn [self] (.getMoistureScenarioTenHourByName self name))))

(defn getMoistureScenarioOneHourByIndex [self index]
  (.then self (fn [self] (.getMoistureScenarioOneHourByIndex self index))))

(defn getMoistureScenarioTenHourByIndex [self index]
  (.then self (fn [self] (.getMoistureScenarioTenHourByIndex self index))))

(defn getIsMoistureScenarioDefinedByIndex [self index]
  (.then self (fn [self] (.getIsMoistureScenarioDefinedByIndex self index))))
