(ns behave.lib.safe-separation-distance-calculator)

;; Auto-generated by hatchet 🪓

(defn SafeSeparationDistanceCalculator []
  (js/Module.SafeSeparationDistanceCalculator.))

;; Calculate

(defn calculate [self]
  (.calculate self))

;; Getters

(defn getBurningCondition [self]
  (.getBurningCondition self))

(defn getSafeSeparationDistance [self lengthUnits]
  (.getSafeSeparationDistance self lengthUnits))

(defn getSafetyZoneSite [self areaUnits]
  (.getSafetyZoneSite self areaUnits))

(defn getSlopeClass [self]
  (.getSlopeClass self))

(defn getSpeedClass [self]
  (.getSpeedClass self))

(defn getVegetationHeight [self lengthUnits]
  (.getVegetationHeight self lengthUnits))

;; Setters

(defn setSpeedClass [self speed]
  (.setSpeedClass self speed))

(defn setSlopeClass [self slope]
  (.setSlopeClass self slope))

(defn setBurningCondition [self condition]
  (.setBurningCondition self condition))

(defn setVegetationHeight [self height lengthUnits]
  (.setVegetationHeight self height lengthUnits))

(def ^:export ns-public-fns (update-keys (ns-publics 'behave.lib.safe-separation-distance-calculator) name))
