(ns behave.lib.species-master-table)

;; Auto-generated by hatchet 🪓

(defn init []
  (js/Module.SpeciesMasterTable.))

(defn initializeMasterTable [self]
  (.then self (fn [self] (.initializeMasterTable self))))

(defn getSpeciesTableIndexFromSpeciesCode [self speciesCode]
  (.then self (fn [self] (.getSpeciesTableIndexFromSpeciesCode self speciesCode))))

(defn getSpeciesTableIndexFromSpeciesCodeAndEquationType [self speciesCode equationType]
  (.then self (fn [self] (.getSpeciesTableIndexFromSpeciesCodeAndEquationType self speciesCode equationType))))

(defn insertRecord [self speciesCode scientificName commonName mortalityEquation brkEqu crownCoefficientCode region1 region2 region3 region4 equationType crownDamageEquationCode]
  (.then self (fn [self] (.insertRecord self speciesCode scientificName commonName mortalityEquation brkEqu crownCoefficientCode region1 region2 region3 region4 equationType crownDamageEquationCode))))
