(ns behave.lib.surface)

;; Auto-generated by hatchet 🪓
(defn init [fuelModels]
  (js/Module.SIGSurface. fuelModels))

(defn setFuelModelNumber [self fuelModelNumber]
  (.setFuelModelNumber self fuelModelNumber))

(defn getSlopeFactor [self]
  (.getSlopeFactor self))

(defn getFireEccentricity [self]
  (.getFireEccentricity self))

(defn setWindAdjustmentFactorCalculationMethod [self windAdjustmentFactorCalculationMethod]
  (.setWindAdjustmentFactorCalculationMethod self windAdjustmentFactorCalculationMethod))

(defn getMoistureHundredHour [self moistureUnits]
  (.getMoistureHundredHour self moistureUnits))

(defn isFuelDynamic [self fuelModelNumber]
  (.isFuelDynamic self fuelModelNumber))

(defn getFuelModelNumber [self]
  (.getFuelModelNumber self))

(defn setWindHeightInputMode [self windHeightInputMode]
  (.setWindHeightInputMode self windHeightInputMode))

(defn setTwoFuelModelsMethod [self twoFuelModelsMethod]
  (.setTwoFuelModelsMethod self twoFuelModelsMethod))

(defn getWindDirection [self]
  (.getWindDirection self))

(defn getHeatPerUnitArea [self heatPerUnitAreaUnits]
  (.getHeatPerUnitArea self heatPerUnitAreaUnits))

(defn getFuelSavrLiveWoody [self fuelModelNumber savrUnits]
  (.getFuelSavrLiveWoody self fuelModelNumber savrUnits))

(defn setMoistureOneHour [self moistureOneHour moistureUnits]
  (.setMoistureOneHour self moistureOneHour moistureUnits))

(defn getFuelName [self fuelModelNumber]
  (.getFuelName self fuelModelNumber))

(defn setSlope [self slope slopeUnits]
  (.setSlope self slope slopeUnits))

(defn setCanopyHeight [self canopyHeight canopyHeightUnits]
  (.setCanopyHeight self canopyHeight canopyHeightUnits))

(defn getMoistureLiveWoody [self moistureUnits]
  (.getMoistureLiveWoody self moistureUnits))

(defn getFuelLoadLiveWoody [self fuelModelNumber loadingUnits]
  (.getFuelLoadLiveWoody self fuelModelNumber loadingUnits))

(defn isAllFuelLoadZero [self fuelModelNumber]
  (.isAllFuelLoadZero self fuelModelNumber))

(defn getWindAndSpreadOrientationMode [self]
  (.getWindAndSpreadOrientationMode self))

(defn getDirectionOfMaxSpread [self]
  (.getDirectionOfMaxSpread self))

(defn getSpreadRateInDirectionOfInterest [self spreadRateUnits]
  (.getSpreadRateInDirectionOfInterest self spreadRateUnits))

(defn getEllipticalA [self lengthUnits elapsedTime timeUnits]
  (.getEllipticalA self lengthUnits elapsedTime timeUnits))

(defn getWindSpeed [self windSpeedUnits windHeightInputMode]
  (.getWindSpeed self windSpeedUnits windHeightInputMode))

(defn setMoistureTenHour [self moistureTenHour moistureUnits]
  (.setMoistureTenHour self moistureTenHour moistureUnits))

(defn getFuelHeatOfCombustionLive [self fuelModelNumber heatOfCombustionUnits]
  (.getFuelHeatOfCombustionLive self fuelModelNumber heatOfCombustionUnits))

(defn getFuelHeatOfCombustionDead [self fuelModelNumber heatOfCombustionUnits]
  (.getFuelHeatOfCombustionDead self fuelModelNumber heatOfCombustionUnits))

(defn getFuelMoistureOfExtinctionDead [self fuelModelNumber moistureUnits]
  (.getFuelMoistureOfExtinctionDead self fuelModelNumber moistureUnits))

(defn getEllipticalB [self lengthUnits elapsedTime timeUnits]
  (.getEllipticalB self lengthUnits elapsedTime timeUnits))

(defn getReactionIntensity [self reactiontionIntensityUnits]
  (.getReactionIntensity self reactiontionIntensityUnits))

(defn getAspect [self]
  (.getAspect self))

(defn getMoistureLiveHerbaceous [self moistureUnits]
  (.getMoistureLiveHerbaceous self moistureUnits))

(defn getFuelCode [self fuelModelNumber]
  (.getFuelCode self fuelModelNumber))

(defn setMoistureLiveHerbaceous [self moistureLiveHerbaceous moistureUnits]
  (.setMoistureLiveHerbaceous self moistureLiveHerbaceous moistureUnits))

(defn operator= [self rhs]
  (.operator= self rhs))

(defn isUsingTwoFuelModels [self]
  (.isUsingTwoFuelModels self))

(defn setUserProvidedWindAdjustmentFactor [self userProvidedWindAdjustmentFactor]
  (.setUserProvidedWindAdjustmentFactor self userProvidedWindAdjustmentFactor))

(defn updateSurfaceInputsForTwoFuelModels [self firstFuelModelNumber secondFuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode firstFuelModelCoverage firstFuelModelCoverageUnits twoFuelModelsMethod slope slopeUnits aspect canopyCover canopyCoverUnits canopyHeight canopyHeightUnits crownRatio]
  (.updateSurfaceInputsForTwoFuelModels self firstFuelModelNumber secondFuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode firstFuelModelCoverage firstFuelModelCoverageUnits twoFuelModelsMethod slope slopeUnits aspect canopyCover canopyCoverUnits canopyHeight canopyHeightUnits crownRatio))

(defn isFuelModelReserved [self fuelModelNumber]
  (.isFuelModelReserved self fuelModelNumber))

(defn getWindHeightInputMode [self]
  (.getWindHeightInputMode self))

(defn getEllipticalC [self lengthUnits elapsedTime timeUnits]
  (.getEllipticalC self lengthUnits elapsedTime timeUnits))

(defn setWindDirection [self windDirection]
  (.setWindDirection self windDirection))

(defn getResidenceTime [self timeUnits]
  (.getResidenceTime self timeUnits))

(defn getFuelSavrOneHour [self fuelModelNumber savrUnits]
  (.getFuelSavrOneHour self fuelModelNumber savrUnits))

(defn setWindAndSpreadOrientationMode [self windAndSpreadOrientationMode]
  (.setWindAndSpreadOrientationMode self windAndSpreadOrientationMode))

(defn getFirePerimeter [self lengthUnits elapsedTime timeUnits]
  (.getFirePerimeter self lengthUnits elapsedTime timeUnits))

(defn getFuelSavrLiveHerbaceous [self fuelModelNumber savrUnits]
  (.getFuelSavrLiveHerbaceous self fuelModelNumber savrUnits))

(defn setAspect [self aspect]
  (.setAspect self aspect))

(defn getFuelLoadLiveHerbaceous [self fuelModelNumber loadingUnits]
  (.getFuelLoadLiveHerbaceous self fuelModelNumber loadingUnits))

(defn setMoistureHundredHour [self moistureHundredHour moistureUnits]
  (.setMoistureHundredHour self moistureHundredHour moistureUnits))

(defn getBulkDensity [self densityUnits]
  (.getBulkDensity self densityUnits))

(defn getFireArea [self areaUnits elapsedTime timeUnits]
  (.getFireArea self areaUnits elapsedTime timeUnits))

(defn getHeatSink [self heatSinkUnits]
  (.getHeatSink self heatSinkUnits))

(defn setCrownRatio [self crownRatio]
  (.setCrownRatio self crownRatio))

(defn getFuelLoadTenHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadTenHour self fuelModelNumber loadingUnits))

(defn initializeMembers [self]
  (.initializeMembers self))

(defn getSlope [self slopeUnits]
  (.getSlope self slopeUnits))

(defn calculateFlameLength [self firelineIntensity]
  (.calculateFlameLength self firelineIntensity))

(defn doSurfaceRunInDirectionOfInterest [self directionOfInterest]
  (.doSurfaceRunInDirectionOfInterest self directionOfInterest))

(defn setMoistureLiveWoody [self moistureLiveWoody moistureUnits]
  (.setMoistureLiveWoody self moistureLiveWoody moistureUnits))

(defn getCrownRatio [self]
  (.getCrownRatio self))

(defn getCanopyHeight [self canopyHeightUnits]
  (.getCanopyHeight self canopyHeightUnits))

(defn setSecondFuelModelNumber [self secondFuelModelNumber]
  (.setSecondFuelModelNumber self secondFuelModelNumber))

(defn setCanopyCover [self canopyCover coverUnits]
  (.setCanopyCover self canopyCover coverUnits))

(defn setWindSpeed [self windSpeed windSpeedUnits windHeightInputMode]
  (.setWindSpeed self windSpeed windSpeedUnits windHeightInputMode))

(defn getMoistureOneHour [self moistureUnits]
  (.getMoistureOneHour self moistureUnits))

(defn getFuelLoadOneHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadOneHour self fuelModelNumber loadingUnits))

(defn setFuelModels [self fuelModels]
  (.setFuelModels self fuelModels))

(defn doSurfaceRunInDirectionOfMaxSpread [self]
  (.doSurfaceRunInDirectionOfMaxSpread self))

(defn updateSurfaceInputs [self fuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio]
  (.updateSurfaceInputs self fuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio))

(defn getMoistureTenHour [self moistureUnits]
  (.getMoistureTenHour self moistureUnits))

(defn getSpreadRate [self spreadRateUnits]
  (.getSpreadRate self spreadRateUnits))

(defn getFuelLoadHundredHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadHundredHour self fuelModelNumber loadingUnits))

(defn getFirelineIntensity [self firelineIntensityUnits]
  (.getFirelineIntensity self firelineIntensityUnits))

(defn getFireLengthToWidthRatio [self]
  (.getFireLengthToWidthRatio self))

(defn setFirstFuelModelNumber [self firstFuelModelNumber]
  (.setFirstFuelModelNumber self firstFuelModelNumber))

(defn setTwoFuelModelsFirstFuelModelCoverage [self firstFuelModelCoverage coverUnits]
  (.setTwoFuelModelsFirstFuelModelCoverage self firstFuelModelCoverage coverUnits))

(defn isFuelModelDefined [self fuelModelNumber]
  (.isFuelModelDefined self fuelModelNumber))

(defn getWindAdjustmentFactorCalculationMethod [self]
  (.getWindAdjustmentFactorCalculationMethod self))

(defn getFuelbedDepth [self fuelModelNumber lengthUnits]
  (.getFuelbedDepth self fuelModelNumber lengthUnits))

(defn getFlameLength [self flameLengthUnits]
  (.getFlameLength self flameLengthUnits))

(defn updateSurfaceInputsForPalmettoGallbery [self moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode ageOfRough heightOfUnderstory palmettoCoverage overstoryBasalArea slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio]
  (.updateSurfaceInputsForPalmettoGallbery self moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode ageOfRough heightOfUnderstory palmettoCoverage overstoryBasalArea slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio))

(defn getCanopyCover [self coverUnits]
  (.getCanopyCover self coverUnits))

(defn updateSurfaceInputsForWesternAspen [self aspenFuelModelNumber aspenCuringLevel aspenFireSeverity DBH moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio]
  (.updateSurfaceInputsForWesternAspen self aspenFuelModelNumber aspenCuringLevel aspenFireSeverity DBH moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio))

(defn getMidflameWindspeed [self windSpeedUnits]
  (.getMidflameWindspeed self windSpeedUnits))
