(ns behave.lib.surface
  (:require [behave.lib.fuel-models :as fuel-models]
            [behave.lib.moisture-scenarios :as moisture-scenarios]))

;; Auto-generated by hatchet 🪓

(defn init
  ([]
   (init (fuel-models/init) (moisture-scenarios/init)))
  ([fuelModels]
   (init fuelModels (moisture-scenarios/init)))
  ([fuelModels moistureScenarios]
   (let [module (js/Module.SIGSurface. fuelModels)]
     (.setMoistureScenarios module moistureScenarios)
     module)))

(defn calculateFlameLength [self firelineIntensity firelineIntensityUnits flameLengthUnits]
  (.calculateFlameLength self firelineIntensity firelineIntensityUnits flameLengthUnits))

(defn calculateScorchHeight [self firelineIntensity firelineIntensityUnits midFlameWindSpeed windSpeedUnits airTemperature temperatureUnits scorchHeightUnits]
  (.calculateScorchHeight self firelineIntensity firelineIntensityUnits midFlameWindSpeed windSpeedUnits airTemperature temperatureUnits scorchHeightUnits))

(defn doSurfaceRun [self]
  (.doSurfaceRun self))

(defn doSurfaceRunInDirectionOfInterest [self directionOfInterest directionMode]
  (.doSurfaceRunInDirectionOfInterest self directionOfInterest directionMode))

(defn doSurfaceRunInDirectionOfMaxSpread [self]
  (.doSurfaceRunInDirectionOfMaxSpread self))

(defn getAgeOfRough [self]
  (.getAgeOfRough self))

(defn getAspect [self]
  (.getAspect self))

(defn getAspenCuringLevel [self curingLevelUnits]
  (.getAspenCuringLevel self curingLevelUnits))

(defn getAspenDBH [self dbhUnits]
  (.getAspenDBH self dbhUnits))

(defn getAspenFireSeverity [self]
  (.getAspenFireSeverity self))

(defn getAspenFuelModelNumber [self]
  (.getAspenFuelModelNumber self))

(defn getAspenLoadDeadOneHour [self loadingUnits]
  (.getAspenLoadDeadOneHour self loadingUnits))

(defn getAspenLoadDeadTenHour [self loadingUnits]
  (.getAspenLoadDeadTenHour self loadingUnits))

(defn getAspenLoadLiveHerbaceous [self loadingUnits]
  (.getAspenLoadLiveHerbaceous self loadingUnits))

(defn getAspenLoadLiveWoody [self loadingUnits]
  (.getAspenLoadLiveWoody self loadingUnits))

(defn getAspenSavrDeadOneHour [self savrUnits]
  (.getAspenSavrDeadOneHour self savrUnits))

(defn getAspenSavrDeadTenHour [self savrUnits]
  (.getAspenSavrDeadTenHour self savrUnits))

(defn getAspenSavrLiveHerbaceous [self savrUnits]
  (.getAspenSavrLiveHerbaceous self savrUnits))

(defn getAspenSavrLiveWoody [self savrUnits]
  (.getAspenSavrLiveWoody self savrUnits))

(defn getBackingDirection [self]
  (.getDirectionOfBacking self))

(defn getBackingFlameLength [self lengthUnits]
  (.getBackingFlameLength self lengthUnits))

(defn getBackingFirelineIntensity [self firelineIntensityUnits]
  (.getBackingFirelineIntensity self firelineIntensityUnits))

(defn getBackingSpreadDistance [self lengthUnits]
  (.getBackingSpreadDistance self lengthUnits))

(defn getBackingSpreadRate [self spreadRateUnits]
  (.getBackingSpreadRate self spreadRateUnits))

(defn getBulkDensity [self densityUnits]
  (.getBulkDensity self densityUnits))

(defn getCanopyCover [self coverUnits]
  (.getCanopyCover self coverUnits))

(defn getCanopyHeight [self canopyHeightUnits]
  (.getCanopyHeight self canopyHeightUnits))

(defn getChaparralAge [self ageUnits]
  (.getChaparralAge self ageUnits))

(defn getChaparralDaysSinceMayFirst [self]
  (.getChaparralDaysSinceMayFirst self))

(defn getChaparralDeadFuelFraction [self]
  (.getChaparralDeadFuelFraction self))

(defn getChaparralDeadMoistureOfExtinction [self moistureUnits]
  (.getChaparralDeadMoistureOfExtinction self moistureUnits))

(defn getChaparralDensity [self lifeState sizeClass densityUnits]
  (.getChaparralDensity self lifeState sizeClass densityUnits))

(defn getChaparralEffectiveSilicaContent [self lifeState sizeClass]
  (.getChaparralEffectiveSilicaContent self lifeState sizeClass))

(defn getChaparralFuelBedDepth [self depthUnits]
  (.getChaparralFuelBedDepth self depthUnits))

(defn getChaparralFuelDeadLoadFraction [self]
  (.getChaparralFuelDeadLoadFraction self))

(defn getChaparralFuelLoadInputMode [self]
  (.getChaparralFuelLoadInputMode self))

(defn getChaparralFuelType [self]
  (.getChaparralFuelType self))

(defn getChaparralHeatOfCombustion [self lifeState sizeClass heatOfCombustionUnits]
  (.getChaparralHeatOfCombustion self lifeState sizeClass heatOfCombustionUnits))

(defn getChaparralLiveMoistureOfExtinction [self moistureUnits]
  (.getChaparralLiveMoistureOfExtinction self moistureUnits))

(defn getChaparralLoad [self lifeState sizeClass loadingUnits]
  (.getChaparralLoad self lifeState sizeClass loadingUnits))

(defn getChaparralMoisture [self lifeState sizeClass moistureUnits]
  (.getChaparralMoisture self lifeState sizeClass moistureUnits))

(defn getChaparralSavr [self lifeState sizeClass savrUnits]
  (.getChaparralSavr self lifeState sizeClass savrUnits))

(defn getChaparralTotalDeadFuelLoad [self loadingUnits]
  (.getChaparralTotalDeadFuelLoad self loadingUnits))

(defn getChaparralTotalFuelLoad [self loadingUnits]
  (.getChaparralTotalFuelLoad self loadingUnits))

(defn getChaparralTotalLiveFuelLoad [self loadingUnits]
  (.getChaparralTotalLiveFuelLoad self loadingUnits))

(defn getChaparralTotalSilicaContent [self lifeState sizeClass]
  (.getChaparralTotalSilicaContent self lifeState sizeClass))

(defn getCharacteristicMoistureByLifeState [self lifeState moistureUnits]
  (.getCharacteristicMoistureByLifeState self lifeState moistureUnits))

(defn getCharacteristicMoistureDead [self moistureUnits]
  (.getCharacteristicMoistureDead self moistureUnits))

(defn getCharacteristicMoistureLive [self moistureUnits]
  (.getCharacteristicMoistureLive self moistureUnits))

(defn getCharacteristicSAVR [self savrUnits]
  (.getCharacteristicSAVR self savrUnits))

(defn getCrownRatio [self crownRatioUnits]
  (.getCrownRatio self crownRatioUnits))

(defn getDirectionOfInterest [self]
  (.getDirectionOfInterest self))

(defn getDirectionOfBacking [self]
  (.getDirectionOfBacking self))

(defn getDirectionOfFlanking [self]
  (.getDirectionOfFlanking self))

(defn getDirectionOfMaxSpread [self]
  (.getDirectionOfMaxSpread self))

(defn getElapsedTime [self timeUnits]
  (.getElapsedTime self timeUnits))

(defn getEllipticalA [self lengthUnits]
  (.getEllipticalA self lengthUnits))

(defn getEllipticalB [self lengthUnits]
  (.getEllipticalB self lengthUnits))

(defn getEllipticalC [self lengthUnits]
  (.getEllipticalC self lengthUnits))

(defn getFireArea [self areaUnits]
  (.getFireArea self areaUnits))

(defn getFireEccentricity [self]
  (.getFireEccentricity self))

(defn getFireLength [self lengthUnits]
  (.getFireLength self lengthUnits))

(defn getMaxFireWidth [self lengthUnits]
  (.getMaxFireWidth self lengthUnits))

(defn getFireLengthToWidthRatio [self]
  (.getFireLengthToWidthRatio self))

(defn getFirePerimeter [self lengthUnits]
  (.getFirePerimeter self lengthUnits))

(defn getFirelineIntensity [self firelineIntensityUnits]
  (.getFirelineIntensity self firelineIntensityUnits))

(defn getFlameLength [self flameLengthUnits]
  (.getFlameLength self flameLengthUnits))

(defn getFlankingDirection [self]
  (.getDirectionOfFlanking self))

(defn getFlankingSpreadDistance [self lengthUnits]
  (.getFlankingSpreadDistance self lengthUnits))

(defn getFlankingSpreadRate [self spreadRateUnits]
  (.getFlankingSpreadRate self spreadRateUnits))

(defn getFlankingFlameLength [self lengthUnits]
  (.getFlankingFlameLength self lengthUnits))

(defn getFlankingFirelineIntensity [self lengthUnits]
  (.getFlankingFirelineIntensity self lengthUnits))

(defn getFuelCode [self fuelModelNumber]
  (.getFuelCode self fuelModelNumber))

(defn getFuelHeatOfCombustionDead [self fuelModelNumber heatOfCombustionUnits]
  (.getFuelHeatOfCombustionDead self fuelModelNumber heatOfCombustionUnits))

(defn getFuelHeatOfCombustionLive [self fuelModelNumber heatOfCombustionUnits]
  (.getFuelHeatOfCombustionLive self fuelModelNumber heatOfCombustionUnits))

(defn getFuelLoadHundredHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadHundredHour self fuelModelNumber loadingUnits))

(defn getFuelLoadLiveHerbaceous [self fuelModelNumber loadingUnits]
  (.getFuelLoadLiveHerbaceous self fuelModelNumber loadingUnits))

(defn getFuelLoadLiveWoody [self fuelModelNumber loadingUnits]
  (.getFuelLoadLiveWoody self fuelModelNumber loadingUnits))

(defn getFuelLoadOneHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadOneHour self fuelModelNumber loadingUnits))

(defn getFuelLoadTenHour [self fuelModelNumber loadingUnits]
  (.getFuelLoadTenHour self fuelModelNumber loadingUnits))

(defn getFuelModelNumber [self]
  (.getFuelModelNumber self))

(defn getFuelMoistureOfExtinctionDead [self fuelModelNumber moistureUnits]
  (.getFuelMoistureOfExtinctionDead self fuelModelNumber moistureUnits))

(defn getFuelName [self fuelModelNumber]
  (.getFuelName self fuelModelNumber))

(defn getFuelSavrLiveHerbaceous [self fuelModelNumber savrUnits]
  (.getFuelSavrLiveHerbaceous self fuelModelNumber savrUnits))

(defn getFuelSavrLiveWoody [self fuelModelNumber savrUnits]
  (.getFuelSavrLiveWoody self fuelModelNumber savrUnits))

(defn getFuelSavrOneHour [self fuelModelNumber savrUnits]
  (.getFuelSavrOneHour self fuelModelNumber savrUnits))

(defn getFuelbedDepth [self fuelModelNumber lengthUnits]
  (.getFuelbedDepth self fuelModelNumber lengthUnits))

(defn getHeadingSpreadRate [self spreadRateUnits]
  (.getHeadingSpreadRate self spreadRateUnits))

(defn getHeadingToBackingRatio [self]
  (.getHeadingToBackingRatio self))

(defn getHeatPerUnitArea [self heatPerUnitAreaUnits]
  (.getHeatPerUnitArea self heatPerUnitAreaUnits))

(defn getHeatSink [self heatSinkUnits]
  (.getHeatSink self heatSinkUnits))

(defn getHeatSource [self heatSourceUnits]
  (.getHeatSource self heatSourceUnits))

(defn getHeightOfUnderstory [self heightUnits]
  (.getHeightOfUnderstory self heightUnits))

(defn getIsMoistureScenarioDefinedByIndex [self index]
  (.getIsMoistureScenarioDefinedByIndex self index))

(defn getIsMoistureScenarioDefinedByName [self name]
  (.getIsMoistureScenarioDefinedByName self name))

(defn getIsUsingChaparral [self]
  (.getIsUsingChaparral self))

(defn getIsUsingPalmettoGallberry [self]
  (.getIsUsingPalmettoGallberry self))

(defn getIsUsingWesternAspen [self]
  (.getIsUsingWesternAspen self))

(defn getLiveFuelMoistureOfExtinction [self moistureUnits]
  (.getLiveFuelMoistureOfExtinction self moistureUnits))

(defn getMidflameWindspeed [self windSpeedUnits]
  (.getMidflameWindspeed self windSpeedUnits))

(defn getMoistureDeadAggregateValue [self moistureUnits]
  (.getMoistureDeadAggregateValue self moistureUnits))

(defn getMoistureHundredHour [self moistureUnits]
  (.getMoistureHundredHour self moistureUnits))

(defn getMoistureInputMode [self]
  (.getMoistureInputMode self))

(defn getMoistureLiveAggregateValue [self moistureUnits]
  (.getMoistureLiveAggregateValue self moistureUnits))

(defn getMoistureLiveHerbaceous [self moistureUnits]
  (.getMoistureLiveHerbaceous self moistureUnits))

(defn getMoistureLiveWoody [self moistureUnits]
  (.getMoistureLiveWoody self moistureUnits))

(defn getMoistureOneHour [self moistureUnits]
  (.getMoistureOneHour self moistureUnits))

(defn getMoistureScenarioDescriptionByIndex [self index]
  (.getMoistureScenarioDescriptionByIndex self index))

(defn getMoistureScenarioDescriptionByName [self name]
  (.getMoistureScenarioDescriptionByName self name))

(defn getMoistureScenarioHundredHourByIndex [self index]
  (.getMoistureScenarioHundredHourByIndex self index))

(defn getMoistureScenarioHundredHourByName [self name]
  (.getMoistureScenarioHundredHourByName self name))

(defn getMoistureScenarioIndexByName [self name]
  (.getMoistureScenarioIndexByName self name))

(defn getMoistureScenarioLiveHerbaceousByIndex [self index]
  (.getMoistureScenarioLiveHerbaceousByIndex self index))

(defn getMoistureScenarioLiveHerbaceousByName [self name]
  (.getMoistureScenarioLiveHerbaceousByName self name))

(defn getMoistureScenarioLiveWoodyByIndex [self index]
  (.getMoistureScenarioLiveWoodyByIndex self index))

(defn getMoistureScenarioLiveWoodyByName [self name]
  (.getMoistureScenarioLiveWoodyByName self name))

(defn getMoistureScenarioNameByIndex [self index]
  (.getMoistureScenarioNameByIndex self index))

(defn getMoistureScenarioOneHourByIndex [self index]
  (.getMoistureScenarioOneHourByIndex self index))

(defn getMoistureScenarioOneHourByName [self name]
  (.getMoistureScenarioOneHourByName self name))

(defn getMoistureScenarioTenHourByIndex [self index]
  (.getMoistureScenarioTenHourByIndex self index))

(defn getMoistureScenarioTenHourByName [self name]
  (.getMoistureScenarioTenHourByName self name))

(defn getMoistureTenHour [self moistureUnits]
  (.getMoistureTenHour self moistureUnits))

(defn getNumberOfMoistureScenarios [self]
  (.getNumberOfMoistureScenarios self))

(defn getOverstoryBasalArea [self basalAreaUnits]
  (.getOverstoryBasalArea self basalAreaUnits))

(defn getPackingRatio [self]
  (.getPackingRatio self))

(defn getPalmettoGallberryCoverage [self coverUnits]
  (.getPalmettoGallberryCoverage self coverUnits))

(defn getPalmettoGallberryHeatOfCombustionDead [self heatOfCombustionUnits]
  (.getPalmettoGallberryHeatOfCombustionDead self heatOfCombustionUnits))

(defn getPalmettoGallberryHeatOfCombustionLive [self heatOfCombustionUnits]
  (.getPalmettoGallberryHeatOfCombustionLive self heatOfCombustionUnits))

(defn getPalmettoGallberryMoistureOfExtinctionDead [self moistureUnits]
  (.getPalmettoGallberryMoistureOfExtinctionDead self moistureUnits))

(defn getPalmettoGallberyDeadFoliageLoad [self loadingUnits]
  (.getPalmettoGallberyDeadFoliageLoad self loadingUnits))

(defn getPalmettoGallberyDeadOneHourLoad [self loadingUnits]
  (.getPalmettoGallberyDeadOneHourLoad self loadingUnits))

(defn getPalmettoGallberyDeadTenHourLoad [self loadingUnits]
  (.getPalmettoGallberyDeadTenHourLoad self loadingUnits))

(defn getPalmettoGallberyFuelBedDepth [self depthUnits]
  (.getPalmettoGallberyFuelBedDepth self depthUnits))

(defn getPalmettoGallberyLitterLoad [self loadingUnits]
  (.getPalmettoGallberyLitterLoad self loadingUnits))

(defn getPalmettoGallberyLiveFoliageLoad [self loadingUnits]
  (.getPalmettoGallberyLiveFoliageLoad self loadingUnits))

(defn getPalmettoGallberyLiveOneHourLoad [self loadingUnits]
  (.getPalmettoGallberyLiveOneHourLoad self loadingUnits))

(defn getPalmettoGallberyLiveTenHourLoad [self loadingUnits]
  (.getPalmettoGallberyLiveTenHourLoad self loadingUnits))

(defn getReactionIntensity [self reactiontionIntensityUnits]
  (.getReactionIntensity self reactiontionIntensityUnits))

(defn getRelativePackingRatio [self]
  (.getRelativePackingRatio self))

(defn getResidenceTime [self timeUnits]
  (.getResidenceTime self timeUnits))

(defn getSlope [self slopeUnits]
  (.getSlope self slopeUnits))

(defn getSlopeFactor [self]
  (.getSlopeFactor self))

(defn getSpreadDistance [self lengthUnits]
  (.getSpreadDistance self lengthUnits))

(defn getSpreadDistanceInDirectionOfInterest [self lengthUnits]
  (.getSpreadDistanceInDirectionOfInterest self lengthUnits))

(defn getSpreadRate [self spreadRateUnits]
  (.getSpreadRate self spreadRateUnits))

(defn getSpreadRateInDirectionOfInterest [self spreadRateUnits]
  (.getSpreadRateInDirectionOfInterest self spreadRateUnits))

(defn getSurfaceFireReactionIntensityDead [self]
  (.getSurfaceFireReactionIntensityDead self))

(defn getSurfaceFireReactionIntensityForLifeState [self lifeState]
  (.getSurfaceFireReactionIntensityForLifeState self lifeState))

(defn getSurfaceFireReactionIntensityLive [self]
  (.getSurfaceFireReactionIntensityLive self))

(defn getSurfaceRunInDirectionOf [self]
  (.getSurfaceRunInDirectionOf self))

(defn getWindAdjustmentFactor [self]
  (.getWindAdjustmentFactor self))

(defn getWindAdjustmentFactorCalculationMethod [self]
  (.getWindAdjustmentFactorCalculationMethod self))

(defn getWindAndSpreadOrientationMode [self]
  (.getWindAndSpreadOrientationMode self))

(defn getWindDirection [self]
  (.getWindDirection self))

(defn getWindHeightInputMode [self]
  (.getWindHeightInputMode self))

(defn getWindSpeed [self windSpeedUnits windHeightInputMode]
  (.getWindSpeed self windSpeedUnits windHeightInputMode))

(defn getWindUpslopeAlignmentMode [self]
  (.getWindUpslopeAlignmentMode self))

(defn initializeMembers [self]
  (.initializeMembers self))

(defn isAllFuelLoadZero [self fuelModelNumber]
  (.isAllFuelLoadZero self fuelModelNumber))

(defn isFuelDynamic [self fuelModelNumber]
  (.isFuelDynamic self fuelModelNumber))

(defn isFuelModelDefined [self fuelModelNumber]
  (.isFuelModelDefined self fuelModelNumber))

(defn isFuelModelReserved [self fuelModelNumber]
  (.isFuelModelReserved self fuelModelNumber))

(defn isMoistureClassInputNeededForCurrentFuelModel [self moistureClass]
  (.isMoistureClassInputNeededForCurrentFuelModel self moistureClass))

(defn isUsingTwoFuelModels [self]
  (.isUsingTwoFuelModels self))

(defn operator= [self rhs]
  (.operator= self rhs))

(defn setAgeOfRough [self ageOfRough]
  (.setAgeOfRough self ageOfRough))

(defn setAspect [self aspect]
  (.setAspect self aspect))

(defn setAspenCuringLevel [self aspenCuringLevel curingLevelUnits]
  (.setAspenCuringLevel self aspenCuringLevel curingLevelUnits))

(defn setAspenDBH [self dbh dbhUnits]
  (.setAspenDBH self dbh dbhUnits))

(defn setAspenFireSeverity [self aspenFireSeverity]
  (.setAspenFireSeverity self aspenFireSeverity))

(defn setAspenFuelModelNumber [self aspenFuelModelNumber]
  (.setAspenFuelModelNumber self aspenFuelModelNumber))

(defn setCanopyCover [self canopyCover coverUnits]
  (.setCanopyCover self canopyCover coverUnits))

(defn setCanopyHeight [self canopyHeight canopyHeightUnits]
  (.setCanopyHeight self canopyHeight canopyHeightUnits))

(defn setChaparralFuelBedDepth [self chaparralFuelBedDepth depthUnts]
  (.setChaparralFuelBedDepth self chaparralFuelBedDepth depthUnts))

(defn setChaparralFuelDeadLoadFraction [self chaparralFuelDeadLoadFraction]
  (.setChaparralFuelDeadLoadFraction self chaparralFuelDeadLoadFraction))

(defn setChaparralFuelLoadInputMode [self fuelLoadInputMode]
  (.setChaparralFuelLoadInputMode self fuelLoadInputMode))

(defn setChaparralFuelType [self chaparralFuelType]
  (.setChaparralFuelType self chaparralFuelType))

(defn setChaparralTotalFuelLoad [self chaparralTotalFuelLoad fuelLoadUnits]
  (.setChaparralTotalFuelLoad self chaparralTotalFuelLoad fuelLoadUnits))

(defn setCrownRatio [self crownRatio crownRatioUnits]
  (.setCrownRatio self crownRatio crownRatioUnits))

(defn setCurrentMoistureScenarioByIndex [self value]
  (.setCurrentMoistureScenarioByIndex self value))

(defn setCurrentMoistureScenarioByName [self value]
  (.setCurrentMoistureScenarioByName self value))

(defn setDirectionOfInterest [self directionOfInterest]
  (.setDirectionOfInterest self directionOfInterest))

(defn setElapsedTime [self elapsedTime timeUnits]
  (.setElapsedTime self elapsedTime timeUnits))

(defn setFirstFuelModelNumber [self firstFuelModelNumber]
  (.setFirstFuelModelNumber self firstFuelModelNumber))

(defn setFuelModelNumber [self fuelModelNumber]
  (.setFuelModelNumber self fuelModelNumber))

(defn setFuelModels [self fuelModels]
  (.setFuelModels self fuelModels))

(defn setHeightOfUnderstory [self heightOfUnderstory heightUnits]
  (.setHeightOfUnderstory self heightOfUnderstory heightUnits))

(defn setIsUsingChaparral [self isUsingChaparral]
  (.setIsUsingChaparral self isUsingChaparral))

(defn setIsUsingPalmettoGallberry [self isUsingPalmettoGallberry]
  (.setIsUsingPalmettoGallberry self isUsingPalmettoGallberry))

(defn setIsUsingWesternAspen [self isUsingWesternAspen]
  (.setIsUsingWesternAspen self isUsingWesternAspen))

(defn setMoistureDeadAggregate [self moistureDead moistureUnits]
  (.setMoistureDeadAggregate self moistureDead moistureUnits))

(defn setMoistureHundredHour [self moistureHundredHour moistureUnits]
  (.setMoistureHundredHour self moistureHundredHour moistureUnits))

(defn setMoistureInputMode [self moistureInputMode]
  (.setMoistureInputMode self moistureInputMode))

(defn setMoistureLiveAggregate [self moistureLive moistureUnits]
  (.setMoistureLiveAggregate self moistureLive moistureUnits))

(defn setMoistureLiveHerbaceous [self moistureLiveHerbaceous moistureUnits]
  (.setMoistureLiveHerbaceous self moistureLiveHerbaceous moistureUnits))

(defn setMoistureLiveWoody [self moistureLiveWoody moistureUnits]
  (.setMoistureLiveWoody self moistureLiveWoody moistureUnits))

(defn setMoistureOneHour [self moistureOneHour moistureUnits]
  (.setMoistureOneHour self moistureOneHour moistureUnits))

(defn setMoistureScenarioByIndex [self moistureScenarioIndex]
  (.setMoistureScenarioByIndex self moistureScenarioIndex))

(defn setMoistureScenarioByName [self moistureScenarioName]
  (.setMoistureScenarioByName self moistureScenarioName))

(defn setMoistureScenarios [self moistureScenarios]
  (.setMoistureScenarios self moistureScenarios))

(defn setMoistureTenHour [self moistureTenHour moistureUnits]
  (.setMoistureTenHour self moistureTenHour moistureUnits))

(defn setOverstoryBasalArea [self overstoryBasalArea basalAreaUnits]
  (.setOverstoryBasalArea self overstoryBasalArea basalAreaUnits))

(defn setPalmettoCoverage [self palmettoCoverage coverUnits]
  (.setPalmettoCoverage self palmettoCoverage coverUnits))

(defn setSecondFuelModelNumber [self secondFuelModelNumber]
  (.setSecondFuelModelNumber self secondFuelModelNumber))

(defn setSlope [self slope slopeUnits]
  (.setSlope self slope slopeUnits))

(defn setSurfaceFireSpreadDirectionMode [self directionMode]
  (.setSurfaceFireSpreadDirectionMode self directionMode))

(defn setSurfaceRunInDirectionOf [self surfaceRunInDirectionOf]
  (.setSurfaceRunInDirectionOf self surfaceRunInDirectionOf))

(defn setTwoFuelModelsFirstFuelModelCoverage [self firstFuelModelCoverage coverUnits]
  (.setTwoFuelModelsFirstFuelModelCoverage self firstFuelModelCoverage coverUnits))

(defn setTwoFuelModelsMethod [self twoFuelModelsMethod]
  (.setTwoFuelModelsMethod self twoFuelModelsMethod))

(defn setUserProvidedWindAdjustmentFactor [self userProvidedWindAdjustmentFactor]
  (.setUserProvidedWindAdjustmentFactor self userProvidedWindAdjustmentFactor))

(defn setWindAdjustmentFactorCalculationMethod [self windAdjustmentFactorCalculationMethod]
  (.setWindAdjustmentFactorCalculationMethod self windAdjustmentFactorCalculationMethod))

(defn setWindAndSpreadOrientationMode [self windAndSpreadOrientationMode]
  (.setWindAndSpreadOrientationMode self windAndSpreadOrientationMode))

(defn setWindDirection [self windDirection]
  (.setWindDirection self windDirection))

(defn setWindHeightInputMode [self windHeightInputMode]
  (.setWindHeightInputMode self windHeightInputMode))

(defn setWindSpeed [self windSpeed windSpeedUnits]
  (.setWindSpeed self windSpeed windSpeedUnits))

(defn setWindUpslopeAlignmentMode [self windUpslopeAlignmentMode]
  (.setWindUpslopeAlignmentMode self windUpslopeAlignmentMode))

(defn updateSurfaceInputs [self fuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio]
  (.updateSurfaceInputs self fuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio))

(defn updateSurfaceInputsForPalmettoGallbery [self moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode ageOfRough heightOfUnderstory palmettoCoverage overstoryBasalArea basalAreaUnits slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio]
  (.updateSurfaceInputsForPalmettoGallbery self moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode ageOfRough heightOfUnderstory palmettoCoverage overstoryBasalArea basalAreaUnits slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio))

(defn updateSurfaceInputsForTwoFuelModels [self firstFuelModelNumber secondFuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode firstFuelModelCoverage firstFuelModelCoverageUnits twoFuelModelsMethod slope slopeUnits aspect canopyCover canopyCoverUnits canopyHeight canopyHeightUnits crownRatio]
  (.updateSurfaceInputsForTwoFuelModels self firstFuelModelNumber secondFuelModelNumber moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode firstFuelModelCoverage firstFuelModelCoverageUnits twoFuelModelsMethod slope slopeUnits aspect canopyCover canopyCoverUnits canopyHeight canopyHeightUnits crownRatio))

(defn updateSurfaceInputsForWesternAspen [self aspenFuelModelNumber aspenCuringLevel curingLevelUnits aspenFireSeverity dbh dbhUnits moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio]
  (.updateSurfaceInputsForWesternAspen self aspenFuelModelNumber aspenCuringLevel curingLevelUnits aspenFireSeverity dbh dbhUnits moistureOneHour moistureTenHour moistureHundredHour moistureLiveHerbaceous moistureLiveWoody moistureUnits windSpeed windSpeedUnits windHeightInputMode windDirection windAndSpreadOrientationMode slope slopeUnits aspect canopyCover coverUnits canopyHeight canopyHeightUnits crownRatio))
