;; Auto-generated by hatchet 🪓
(ns behave.lib.vapor-pressure-deficit-calculator)

(defn init []
  (js/Module.VaporPressureDeficitCalculator.))

(defn runCalculation [self]
  (.runCalculation self))

(defn setTemperature [self temperature]
  (.setTemperature self temperature))

(defn setRelativeHumidity [self relativeHumidity units]
  (.setRelativeHumidity self relativeHumidity units))

(defn getVaporPressureDeficit [self units]
  (.getVaporPressureDeficit self units))

(def ^:export ns-public-fns (update-keys (ns-publics 'behave.lib.vapor-pressure-deficit-calculator) name))
