// Follows this pattern
// typedef <struct::enum> <struct_enum>;

// Behave Units Enums
typedef AreaUnits::AreaUnitsEnum AreaUnits_AreaUnitsEnum;
typedef LengthUnits::LengthUnitsEnum LengthUnits_LengthUnitsEnum;
typedef LoadingUnits::LoadingUnitsEnum LoadingUnits_LoadingUnitsEnum;
typedef SurfaceAreaToVolumeUnits::SurfaceAreaToVolumeUnitsEnum SurfaceAreaToVolumeUnits_SurfaceAreaToVolumeUnitsEnum;
typedef CoverUnits::CoverUnitsEnum CoverUnits_CoverUnitsEnum;
typedef SpeedUnits::SpeedUnitsEnum SpeedUnits_SpeedUnitsEnum;
typedef ProbabilityUnits::ProbabilityUnitsEnum ProbabilityUnits_ProbabilityUnitsEnum;
typedef MoistureUnits::MoistureUnitsEnum MoistureUnits_MoistureUnitsEnum;
typedef SlopeUnits::SlopeUnitsEnum SlopeUnits_SlopeUnitsEnum;
typedef DensityUnits::DensityUnitsEnum DensityUnits_DensityUnitsEnum;
typedef HeatOfCombustionUnits::HeatOfCombustionUnitsEnum HeatOfCombustionUnits_HeatOfCombustionUnitsEnum;
typedef HeatSinkUnits::HeatSinkUnitsEnum HeatSinkUnits_HeatSinkUnitsEnum;
typedef HeatPerUnitAreaUnits::HeatPerUnitAreaUnitsEnum HeatPerUnitAreaUnits_HeatPerUnitAreaUnitsEnum;
typedef HeatSourceAndReactionIntensityUnits::HeatSourceAndReactionIntensityUnitsEnum HeatSourceAndReactionIntensityUnits_HeatSourceAndReactionIntensityUnitsEnum;
typedef FirelineIntensityUnits::FirelineIntensityUnitsEnum FirelineIntensityUnits_FirelineIntensityUnitsEnum;
typedef TemperatureUnits::TemperatureUnitsEnum TemperatureUnits_TemperatureUnitsEnum;
typedef TimeUnits::TimeUnitsEnum TimeUnits_TimeUnitsEnum;

// containAdapter.h
typedef ContainAdapterEnums::ContainTactic::ContainTacticEnum ContainTactic_ContainTacticEnum;
typedef ContainAdapterEnums::ContainStatus::ContainStatusEnum ContainStatus_ContainStatusEnum;
typedef ContainAdapterEnums::ContainFlank::ContainFlankEnum ContainFlank_ContainFlankEnum;

// surfaceInputs.h
typedef AspenFireSeverity::AspenFireSeverityEnum AspenFireSeverity_AspenFireSeverityEnum;
typedef TwoFuelModelsMethod::TwoFuelModelsMethodEnum TwoFuelModelsMethod_TwoFuelModelsMethodEnum;
typedef WindAdjustmentFactorShelterMethod::WindAdjustmentFactorShelterMethodEnum WindAdjustmentFactorShelterMethod_WindAdjustmentFactorShelterMethodEnum;
typedef WindAdjustmentFactorCalculationMethod::WindAdjustmentFactorCalculationMethodEnum WindAdjustmentFactorCalculationMethod_WindAdjustmentFactorCalculationMethodEnum;
typedef WindAndSpreadOrientationMode::WindAndSpreadOrientationModeEnum WindAndSpreadOrientationMode_WindAndSpreadOrientationModeEnum;
typedef WindHeightInputMode::WindHeightInputModeEnum WindHeightInputMode_WindHeightInputModeEnum;

// crown.h
typedef FireType::FireTypeEnum FireType_FireTypeEnum;

//
typedef double* DoublePtr;

// igniteInputs.h
typedef LightningCharge::LightningChargeEnum LightningCharge_LightningChargeEnum;
typedef IgnitionFuelBedType::IgnitionFuelBedTypeEnum IgnitionFuelBedType_IgnitionFuelBedTypeEnum;
