// Follows this pattern
// typedef <struct::enum> <struct_enum>;

// Behave Units Enums
typedef AreaUnits::AreaUnitsEnum AreaUnits_AreaUnitsEnum;
typedef BasalAreaUnits::BasalAreaUnitsEnum BasalAreaUnits_BasalAreaUnitsEnum;
typedef LengthUnits::LengthUnitsEnum LengthUnits_LengthUnitsEnum;
typedef LoadingUnits::LoadingUnitsEnum LoadingUnits_LoadingUnitsEnum;
typedef SurfaceAreaToVolumeUnits::SurfaceAreaToVolumeUnitsEnum
    SurfaceAreaToVolumeUnits_SurfaceAreaToVolumeUnitsEnum;
typedef FractionUnits::FractionUnitsEnum FractionUnits_FractionUnitsEnum;
typedef SpeedUnits::SpeedUnitsEnum SpeedUnits_SpeedUnitsEnum;
typedef SlopeUnits::SlopeUnitsEnum SlopeUnits_SlopeUnitsEnum;
typedef DensityUnits::DensityUnitsEnum DensityUnits_DensityUnitsEnum;
typedef FirelineIntensityUnits::FirelineIntensityUnitsEnum FirelineIntensityUnits_FirelineIntensityUnitsEnum;
typedef FractionUnits::FractionUnitsEnum FractionUnits_FractionUnitsEnum;
typedef HeatOfCombustionUnits::HeatOfCombustionUnitsEnum HeatOfCombustionUnits_HeatOfCombustionUnitsEnum;
typedef HeatPerUnitAreaUnits::HeatPerUnitAreaUnitsEnum HeatPerUnitAreaUnits_HeatPerUnitAreaUnitsEnum;
typedef HeatSinkUnits::HeatSinkUnitsEnum HeatSinkUnits_HeatSinkUnitsEnum;
typedef HeatSourceAndReactionIntensityUnits::HeatSourceAndReactionIntensityUnitsEnum
    HeatSourceAndReactionIntensityUnits_HeatSourceAndReactionIntensityUnitsEnum;
typedef LengthUnits::LengthUnitsEnum LengthUnits_LengthUnitsEnum;
typedef LoadingUnits::LoadingUnitsEnum LoadingUnits_LoadingUnitsEnum;
typedef PressureUnits::PressureUnitsEnum PressureUnits_PressureUnitsEnum;
typedef SlopeUnits::SlopeUnitsEnum SlopeUnits_SlopeUnitsEnum;
typedef SpeedUnits::SpeedUnitsEnum SpeedUnits_SpeedUnitsEnum;
typedef SurfaceAreaToVolumeUnits::SurfaceAreaToVolumeUnitsEnum
    SurfaceAreaToVolumeUnits_SurfaceAreaToVolumeUnitsEnum;
typedef TemperatureUnits::TemperatureUnitsEnum TemperatureUnits_TemperatureUnitsEnum;
typedef TimeUnits::TimeUnitsEnum TimeUnits_TimeUnitsEnum;

// containAdapter.h
typedef ContainAdapterEnums::ContainTactic::ContainTacticEnum ContainTactic_ContainTacticEnum;
typedef ContainAdapterEnums::ContainStatus::ContainStatusEnum ContainStatus_ContainStatusEnum;
typedef ContainAdapterEnums::ContainFlank::ContainFlankEnum ContainFlank_ContainFlankEnum;

// surfaceInputs.h
typedef AspenFireSeverity::AspenFireSeverityEnum AspenFireSeverity_AspenFireSeverityEnum;
typedef ChaparralFuelType::ChaparralFuelTypeEnum ChaparralFuelType_ChaparralFuelTypeEnum;
typedef ChaparralFuelLoadInputMode::ChaparralFuelInputLoadModeEnum ChaparralFuelLoadInputMode_ChaparralFuelInputLoadModeEnum;
typedef MoistureInputMode::MoistureInputModeEnum MoistureInputMode_MoistureInputModeEnum;
typedef MoistureClassInput::MoistureClassInputEnum MoistureClassInput_MoistureClassInputEnum;
typedef SurfaceFireSpreadDirectionMode::SurfaceFireSpreadDirectionModeEnum
    SurfaceFireSpreadDirectionMode_SurfaceFireSpreadDirectionModeEnum;
typedef TwoFuelModelsMethod::TwoFuelModelsMethodEnum TwoFuelModelsMethod_TwoFuelModelsMethodEnum;
typedef WindAdjustmentFactorShelterMethod::WindAdjustmentFactorShelterMethodEnum
    WindAdjustmentFactorShelterMethod_WindAdjustmentFactorShelterMethodEnum;
typedef WindAdjustmentFactorCalculationMethod::WindAdjustmentFactorCalculationMethodEnum
    WindAdjustmentFactorCalculationMethod_WindAdjustmentFactorCalculationMethodEnum;
typedef WindAndSpreadOrientationMode::WindAndSpreadOrientationModeEnum
    WindAndSpreadOrientationMode_WindAndSpreadOrientationModeEnum;
typedef WindHeightInputMode::WindHeightInputModeEnum WindHeightInputMode_WindHeightInputModeEnum;

// crown.h
typedef FireType::FireTypeEnum FireType_FireTypeEnum;

//
typedef double *DoublePtr;

// fuelModels.h
typedef FuelLifeState::FuelLifeStateEnum FuelLifeState_FuelLifeStateEnum;
typedef FuelConstants::FuelConstantsEnum FuelConstantsEnum_FuelConstantsEnum;

// igniteInputs.h
typedef LightningCharge::LightningChargeEnum LightningCharge_LightningChargeEnum;
typedef IgnitionFuelBedType::IgnitionFuelBedTypeEnum IgnitionFuelBedType_IgnitionFuelBedTypeEnum;

// spotInputs.h
typedef SpotDownWindCanopyMode::SpotDownWindCanopyModeEnum SpotDownWindCanopyMode_SpotDownWindCanopyModeEnum;
typedef SpotTreeSpecies::SpotTreeSpeciesEnum SpotTreeSpecies_SpotTreeSpeciesEnum;
typedef SpotFireLocation::SpotFireLocationEnum SpotFireLocation_SpotFireLocationEnum;

// fineDeadFuelMoistureTool.h
typedef FDFMToolAspectIndex::AspectIndexEnum FDFMToolAspectIndex_AspectIndexEnum;
typedef FDFMToolDryBulbIndex::DryBulbIndexEnum FDFMToolDryBulbIndex_DryBulbIndexEnum;
typedef FDFMToolElevationIndex::ElevationIndexEnum FDFMToolElevationIndex_ElevationIndexEnum;
typedef FDFMToolMonthIndex::MonthIndexEnum FDFMToolMonthIndex_MonthIndexEnum;
typedef FDFMToolRHIndex::RHIndexEnum FDFMToolRHIndex_RHIndexEnum;
typedef FDFMToolShadingIndex::ShadingIndexEnum FDFMToolShadingIndex_ShadingIndexEnum;
typedef FDFMToolSlopeIndex::SlopeIndexEnum FDFMToolSlopeIndex_SlopeIndexEnum;
typedef FDFMToolTimeOfDayIndex::TimeOfDayIndexEnum FDFMToolTimeOfDayIndex_TimeOfDayIndexEnum;

// slopeTool.h
typedef RepresentativeFraction::RepresentativeFractionEnum RepresentativeFraction_RepresentativeFractionEnum;
typedef HorizontalDistanceIndex::HorizontalDistanceIndexEnum HorizontalDistanceIndex_HorizontalDistanceIndexEnum;
