interface ContainForceAdapter {
  void ContainForceAdapter();
  void addResource(double arrival, double production, double duration, Sem_ContainFlank flank, std_string desc, double baseCost, double hourCost);
  double firstArrival(Sem_ContainFlank flank);
  long removeResourceAt(long index);
  long removeResourceWithThisDesc(std_string desc);
  long removeAllResourcesWithThisDesc(std_string desc);
};
