[Prefix="Sem"]
interface ContainForce {
  ContainResource addResource(double arrival, double production, double duration, Sem_ContainFlank flank, byte desc, double baseCost, double hourCost);
  Sem_ContainFlank resourceFlank(long index);
  byte resourceDescription(long index);
  double exhausted(Sem_ContainFlank flank);
  double firstArrival(Sem_ContainFlank flank);
  double nextArrival(double after, double until, Sem_ContainFlank flank);
  double productionRate(double minutesSinceReport, Sem_ContainFlank flank);
  double resourceArrival(long index);
  double resourceBaseCost(long index);
  double resourceCost(long index, double finalTime);
  double resourceDuration(long index);
  double resourceHourCost(long index);
  double resourceProduction(long index);
  long resources();
  void ContainForce(long maxResources);
  void logResources(boolean debug);
};
