interface Safety {
  double getSeparationDistance(LengthUnits_LengthUnitsEnum lengthUnits);
  void setNumberOfEquipment(double numberOfEquipment);
  void calculateSafetyZone();
  void setNumberOfPersonnel(double numberOfPersonnel);
  void setFlameHeight(double flameHeight, LengthUnits_LengthUnitsEnum lengthUnits);
  void updateSafetyInputs(double flameHeight, LengthUnits_LengthUnitsEnum lengthUnits, long numberOfPersonnel, long numberOfEquipment, double areaPerPerson, double areaPerEquipment, AreaUnits_AreaUnitsEnum areaUnits);
  double getSafetyZoneRadius(LengthUnits_LengthUnitsEnum lengthUnits);
  void initializeMembers();
  void setAreaPerPerson(double areaPerPerson, AreaUnits_AreaUnitsEnum areaUnits);
  double getSafetyZoneArea(AreaUnits_AreaUnitsEnum areaUnits);
  void setAreaPerEquipment(double areaPerEquipment, AreaUnits_AreaUnitsEnum areaUnits);
};
