interface SurfaceFuelbedIntermediates {
  void SurfaceFuelbedIntermediates(FuelModelSet fuelModelSet, SurfaceInputs surfaceInputs);
  //SurfaceFuelbedIntermediates operator=(SurfaceFuelbedIntermediates rhs);
  double getAspenMortality();
  double getBulkDensity();
  double getFuelbedDepth();
  double getHeatSink();
  double getMoistureOfExtinctionByLifeState(long lifeState);
  double getPackingRatio();
  double getPalmettoGallberyDeadFoliageLoad();
  double getPalmettoGallberyDeadOneHourLoad();
  double getPalmettoGallberyDeadTenHourLoad();
  double getPalmettoGallberyFuelBedDepth();
  double getPalmettoGallberyLitterLoad();
  double getPalmettoGallberyLiveFoliageLoad();
  double getPalmettoGallberyLiveOneHourLoad();
  double getPalmettoGallberyLiveTenHourLoad();
  double getPropagatingFlux();
  double getRelativePackingRatio();
  double getSigma();
  double getWeightedFuelLoadByLifeState(long lifeState);
  double getWeightedHeatByLifeState(long lifeState);
  double getWeightedMoistureByLifeState(long lifeState);
  double getWeightedSilicaByLifeState(long lifeState);
  void calculateFuelbedIntermediates(long fuelModelNumber);
};
